### ISSUE TITLE
Running Issues

### ISSUE THREAD

**Issue by z4z5** [danecor/VaST#3]
Hi Dane,
I have troubles when running the code.
In this line:

from pridict import priority_dict

I can't find the file 'pridict'. Is it in the file folder 'cypridict'? I can only find the file pridict.so ,but my system is Windows.

Thanks,
z4z5

**Comment by danecor** [comment]
Hi z4z5, were you able to install the cypridict submodule, install cython and cythonize it (i.e. the "Installation" section of the readme?).

**Comment by z4z5** [comment]
Hi Dane,
Thanks for your response. I tried to install the cypridict submodule, install cython and cythonize it.It seems that I successfully ran the install.sh, but when I tried to run 'cython table/hamming.pyx' and 'cython table/hctable.pyx', the error is below:

Error compiling Cython file:
------------------------------------------------------------
...
from libc cimport stdint
^
------------------------------------------------------------

table/hamming.pyx:1:0: 'VaST-master.table.hamming' is not a valid module name

**Comment by z4z5** [comment]
Hi Dane,
Thank you for your reply, the problem has been solved:)
